[build]
  command = "yarn build"
  publish = "build/"
  functions = "functions/"

[context.production]
  command = "yarn build"
  environment = { NODE_ENV = "production"}

[context.branch-deploy]
  command = "yarn build"
  environment = { NODE_ENV = "production"}
