[build]
  command = "yarn build"
  publish = "public/"
  functions = "functions/"

[context.production]
  command = "yarn build"
  environment = { GATSBY_ENV = "production", NODE_ENV = "production"}

[context.branch-deploy]
  command = "yarn build"
  environment = { GATSBY_ENV = "production", NODE_ENV = "production"}
