backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  repo: richpjames/matt-tulloch

publish_mode: editorial_workflow
media_folder: "static/image/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"
site_url: https://tulltulloch.com
display_url: https://tulltulloch.com

collections:
  - name: "shop_items" # Used in routes, e.g., /admin/collections/blog
    label: "Shop items" # Used in the UI
    folder: "static/_shop/items" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: json
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "shop_item",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Blurb", name: "blurb", widget: "text" }
      - { label: "Id", name: "id", widget: "string", comment: "EG A6" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Inventory", name: "inventory", widget: "number" }
      - { label: "Dev price Id", name: "dev_price_id", widget: "hidden" }
      - { label: "Prod price Id", name: "prod_price_id", widget: "hidden" }
      - {
          label: "Status",
          name: "status",
          widget: "select",
          options: ["available", "dead"],
        }
      - { label: "Dimensions", name: "dimensions", widget: "string" }
      - { label: "Images", name: "images", widget: "list" }
      - { label: "Order", name: "order", widget: "number" }
    sortable_fields: ["order"]
